import os
import pandas as pd
import numpy as np

def build_all_research_tables(base_dir):
    meta_dir = os.path.join(base_dir, "metadata")
    rep_dir = os.path.join(base_dir, "reports")
    os.makedirs(meta_dir, exist_ok=True)
    os.makedirs(rep_dir, exist_ok=True)

    # 1. Crop Priority
    crops = [
        {"crop": "Rice", "scientific_name": "Oryza sativa", "category": "Cereals", "major_producing_states": "West Bengal, Uttar Pradesh, Punjab, Andhra Pradesh, Telangana, Odisha", "cultivated_area_mha": 45.5, "production_mt": 130.8, "economic_importance_score": 98.0, "cultivation_importance_score": 100.0, "farmer_impact_score": 100.0, "production_importance_score": 100.0, "disease_pest_impact_score": 95.0, "dataset_feasibility_score": 95.0, "food_security_relevance": "Primary staple food for >65% of Indian population. Core of National Food Security Act.", "industrial_relevance": "Rice bran oil, starch, brewery, poultry feed.", "export_relevance": "India is world #1 rice exporter (> $11B/yr).", "farmer_livelihood_relevance": "Supports >50M smallholder and marginal farm families.", "major_seasons": "Kharif, Rabi, Summer", "major_diseases": "Blast (Magnaporthe oryzae), Brown Spot (Bipolaris oryzae), Bacterial Leaf Blight", "major_pests": "Yellow Stem Borer, Brown Planthopper", "major_abiotic_stresses": "Drought, Submergence/Flood, Salinity", "reason_for_inclusion": "Rank #1 staple cereal; vital for food security and farmer livelihood."},
        {"crop": "Wheat", "scientific_name": "Triticum aestivum", "category": "Cereals", "major_producing_states": "Uttar Pradesh, Madhya Pradesh, Punjab, Haryana, Rajasthan, Bihar", "cultivated_area_mha": 30.5, "production_mt": 110.5, "economic_importance_score": 95.0, "cultivation_importance_score": 92.0, "farmer_impact_score": 95.0, "production_importance_score": 96.0, "disease_pest_impact_score": 90.0, "dataset_feasibility_score": 92.0, "food_security_relevance": "Major rabi cereal staple; core of PDS buffer stocks.", "industrial_relevance": "Flour milling, bakery, confectionery, pasta.", "export_relevance": "Regional buffer and export.", "farmer_livelihood_relevance": "Core winter income for millions of North/Central Indian farmers.", "major_seasons": "Rabi (Winter)", "major_diseases": "Yellow/Stripe Rust (Puccinia striiformis), Brown/Leaf Rust (Puccinia triticina)", "major_pests": "Wheat Aphids, Armyworm", "major_abiotic_stresses": "Terminal heat stress, Drought at CRI", "reason_for_inclusion": "Rank #2 staple food; yellow and brown rusts cause severe epidemics."},
        {"crop": "Cotton", "scientific_name": "Gossypium hirsutum", "category": "Commercial/Fibre", "major_producing_states": "Gujarat, Maharashtra, Telangana, Andhra Pradesh, Rajasthan, Punjab", "cultivated_area_mha": 12.5, "production_mt": 34.0, "economic_importance_score": 96.0, "cultivation_importance_score": 85.0, "farmer_impact_score": 96.0, "production_importance_score": 90.0, "disease_pest_impact_score": 98.0, "dataset_feasibility_score": 88.0, "food_security_relevance": "Cottonseed edible oil and cattle feed cake.", "industrial_relevance": "Core raw material for Indian Textile Industry (~2% GDP).", "export_relevance": "Major foreign exchange earner (cotton, yarn).", "farmer_livelihood_relevance": "Supports ~6M farmers and 45M textile workers.", "major_seasons": "Kharif", "major_diseases": "Bacterial Blight, Cotton Leaf Curl Virus (CLCuV)", "major_pests": "Pink Bollworm, Whitefly, Jassids", "major_abiotic_stresses": "Drought, Waterlogging, Magnesium deficiency", "reason_for_inclusion": "Key commercial fibre cash crop; high vulnerability to CLCuV and blight."},
        {"crop": "Tomato", "scientific_name": "Solanum lycopersicum", "category": "Horticultural", "major_producing_states": "Andhra Pradesh, Madhya Pradesh, Karnataka, Gujarat, Odisha, Maharashtra", "cultivated_area_mha": 0.84, "production_mt": 20.5, "economic_importance_score": 92.0, "cultivation_importance_score": 75.0, "farmer_impact_score": 94.0, "production_importance_score": 88.0, "disease_pest_impact_score": 96.0, "dataset_feasibility_score": 98.0, "food_security_relevance": "National TOP mission staple; essential daily nutrition.", "industrial_relevance": "Puree, paste, ketchup, lycopene.", "export_relevance": "Exported to Middle East and South Asia.", "farmer_livelihood_relevance": "High cash turnover crop for small/marginal farmers.", "major_seasons": "Kharif, Rabi, Summer", "major_diseases": "Early Blight, Late Blight, Bacterial Spot, TYLCV", "major_pests": "Pinworm, Whiteflies, Spider Mites", "major_abiotic_stresses": "Blossom End Rot, Sunscald", "reason_for_inclusion": "High-value horticulture crop with rich verified pathogen visual symptoms."},
        {"crop": "Potato", "scientific_name": "Solanum tuberosum", "category": "Horticultural", "major_producing_states": "Uttar Pradesh, West Bengal, Bihar, Gujarat, Madhya Pradesh, Punjab", "cultivated_area_mha": 2.2, "production_mt": 53.5, "economic_importance_score": 94.0, "cultivation_importance_score": 82.0, "farmer_impact_score": 92.0, "production_importance_score": 94.0, "disease_pest_impact_score": 94.0, "dataset_feasibility_score": 96.0, "food_security_relevance": "Major tuber staple across Indo-Gangetic Plains.", "industrial_relevance": "Chips, French fries, dehydrated flakes, starch.", "export_relevance": "Seed potato and fresh potato export.", "farmer_livelihood_relevance": "Cash crop supporting >8M farm households.", "major_seasons": "Rabi (Plains), Summer (Hills)", "major_diseases": "Late Blight (Phytophthora infestans), Early Blight", "major_pests": "Tuber Moth, Aphids", "major_abiotic_stresses": "Frost damage, Heat sprouting", "reason_for_inclusion": "Major vegetable tuber; Late Blight can cause 100% crop loss in 7 days."},
        {"crop": "Chilli", "scientific_name": "Capsicum annuum", "category": "Horticultural", "major_producing_states": "Andhra Pradesh, Telangana, Madhya Pradesh, Karnataka, West Bengal", "cultivated_area_mha": 0.85, "production_mt": 2.1, "economic_importance_score": 91.0, "cultivation_importance_score": 74.0, "farmer_impact_score": 93.0, "production_importance_score": 85.0, "disease_pest_impact_score": 95.0, "dataset_feasibility_score": 94.0, "food_security_relevance": "Essential Indian spice rich in Vitamins A and C.", "industrial_relevance": "Capsaicin extraction, oleoresin, spice powders.", "export_relevance": "India is world #1 exporter (>40% global share).", "farmer_livelihood_relevance": "High-margin cash crop for smallholders.", "major_seasons": "Kharif, Rabi", "major_diseases": "Chilli Leaf Curl Virus (ChiLCV), Bacterial Spot", "major_pests": "Chilli Thrips, Yellow Mites", "major_abiotic_stresses": "High heat flower drop, Drought", "reason_for_inclusion": "Premier spice export crop with prominent leaf curl and bacterial symptoms."},
        {"crop": "Maize", "scientific_name": "Zea mays", "category": "Cereals", "major_producing_states": "Karnataka, Madhya Pradesh, Maharashtra, Bihar, Rajasthan, Telangana", "cultivated_area_mha": 9.8, "production_mt": 33.7, "economic_importance_score": 89.0, "cultivation_importance_score": 84.0, "farmer_impact_score": 88.0, "production_importance_score": 90.0, "disease_pest_impact_score": 92.0, "dataset_feasibility_score": 92.0, "food_security_relevance": "Food staple in tribal areas; animal feed grain.", "industrial_relevance": "Starch, ethanol blending, corn oil, bioplastics.", "export_relevance": "Exported to Southeast Asian feed markets.", "farmer_livelihood_relevance": "Fast-growing high-yield cereal for dryland farmers.", "major_seasons": "Kharif, Rabi", "major_diseases": "Northern Leaf Blight (Exserohilum turcicum), Common Rust", "major_pests": "Fall Armyworm (Spodoptera frugiperda), Stem Borer", "major_abiotic_stresses": "Waterlogging, Drought at tasseling", "reason_for_inclusion": "Industrial cereal with distinct foliar blight and invasive Fall Armyworm damage."}
    ]
    df_crops = pd.DataFrame(crops)
    df_crops["priority_score"] = (
        0.25 * df_crops["economic_importance_score"] +
        0.20 * df_crops["cultivation_importance_score"] +
        0.20 * df_crops["farmer_impact_score"] +
        0.15 * df_crops["production_importance_score"] +
        0.10 * df_crops["disease_pest_impact_score"] +
        0.10 * df_crops["dataset_feasibility_score"]
    ).round(2)
    df_crops = df_crops.sort_values(by="priority_score", ascending=False).reset_index(drop=True)
    df_crops["rank"] = df_crops.index + 1
    df_crops.to_csv(os.path.join(meta_dir, "crop_priority.csv"), index=False)

    # 2. Disease Validation
    disease_val = [
        {"crop": "Rice", "condition": "Rice Blast", "category": "Fungal Disease", "causal_agent": "Magnaporthe oryzae", "symptoms": "Spindle-shaped elliptical lesions with grey center", "india_relevance": "HIGH (Endemic in WB, Punjab, AP, TN)", "image_detectability": "HIGH", "source": "ICAR-NRRI Cuttack / IARI Pusa", "confidence": "HIGH"},
        {"crop": "Rice", "condition": "Rice Brown Spot", "category": "Fungal Disease", "causal_agent": "Bipolaris oryzae", "symptoms": "Small circular to oval brown spots with yellow halo", "india_relevance": "HIGH (Bengal Famine pathogen; Eastern India)", "image_detectability": "HIGH", "source": "ICAR-NRRI Cuttack", "confidence": "HIGH"},
        {"crop": "Rice", "condition": "Rice Bacterial Blight", "category": "Bacterial Disease", "causal_agent": "Xanthomonas oryzae pv. oryzae", "symptoms": "Water-soaked wavy marginal yellow-white striping", "india_relevance": "HIGH (Major in irrigated and flood plains)", "image_detectability": "HIGH", "source": "ICAR-IARI Plant Pathology", "confidence": "HIGH"},
        {"crop": "Rice", "condition": "Rice Healthy", "category": "Healthy", "causal_agent": "None", "symptoms": "Uniform clean green leaf blade", "india_relevance": "HIGH", "image_detectability": "HIGH", "source": "ICAR Extension Guide", "confidence": "HIGH"},
        {"crop": "Wheat", "condition": "Wheat Yellow Rust", "category": "Fungal Disease", "causal_agent": "Puccinia striiformis", "symptoms": "Bright yellow linear parallel stripe pustules", "india_relevance": "HIGH (NW India - Punjab, Haryana, UP)", "image_detectability": "HIGH", "source": "ICAR-IIWBR Karnal", "confidence": "HIGH"},
        {"crop": "Wheat", "condition": "Wheat Brown Rust", "category": "Fungal Disease", "causal_agent": "Puccinia triticina", "symptoms": "Small orange-brown pustules scattered on leaf", "india_relevance": "HIGH (Central & Peninsular India)", "image_detectability": "HIGH", "source": "ICAR-IIWBR Karnal", "confidence": "HIGH"},
        {"crop": "Wheat", "condition": "Wheat Healthy", "category": "Healthy", "causal_agent": "None", "symptoms": "Clean upright green blade", "india_relevance": "HIGH", "image_detectability": "HIGH", "source": "ICAR-IIWBR Karnal", "confidence": "HIGH"},
        {"crop": "Cotton", "condition": "Cotton Bacterial Blight", "category": "Bacterial Disease", "causal_agent": "Xanthomonas citri pv. malvacearum", "symptoms": "Angular vein-delimited reddish-brown spots", "india_relevance": "HIGH (Central & South Cotton Zones)", "image_detectability": "HIGH", "source": "ICAR-CICR Nagpur", "confidence": "HIGH"},
        {"crop": "Cotton", "condition": "Cotton Leaf Curl Virus", "category": "Viral Disease", "causal_agent": "Cotton Leaf Curl Virus (CLCuV)", "symptoms": "Upward cupping, vein thickening and enation", "india_relevance": "HIGH (North Cotton Zone)", "image_detectability": "HIGH", "source": "ICAR-CICR Nagpur", "confidence": "HIGH"},
        {"crop": "Cotton", "condition": "Cotton Healthy", "category": "Healthy", "causal_agent": "None", "symptoms": "Broad dark-green palmate lobed leaf", "india_relevance": "HIGH", "image_detectability": "HIGH", "source": "ICAR-CICR Nagpur", "confidence": "HIGH"},
        {"crop": "Tomato", "condition": "Tomato Early Blight", "category": "Fungal Disease", "causal_agent": "Alternaria solani", "symptoms": "Concentric ring target-board lesions with halo", "india_relevance": "HIGH (All tomato belts year-round)", "image_detectability": "HIGH", "source": "ICAR-IIHR Bengaluru", "confidence": "HIGH"},
        {"crop": "Tomato", "condition": "Tomato Late Blight", "category": "Fungal Disease", "causal_agent": "Phytophthora infestans", "symptoms": "Purplish-brown water-soaked expanding lesions", "india_relevance": "HIGH (Cool humid rabi seasons)", "image_detectability": "HIGH", "source": "ICAR-IIHR Bengaluru", "confidence": "HIGH"},
        {"crop": "Tomato", "condition": "Tomato Bacterial Spot", "category": "Bacterial Disease", "causal_agent": "Xanthomonas campestris pv. vesicatoria", "symptoms": "Small dark brown spots with greasy halos", "india_relevance": "HIGH (Warm rainy kharif)", "image_detectability": "HIGH", "source": "ICAR-IIHR Bengaluru", "confidence": "HIGH"},
        {"crop": "Tomato", "condition": "Tomato Yellow Leaf Curl", "category": "Viral Disease", "causal_agent": "TYLCV (Begomovirus / Whitefly)", "symptoms": "Severe upward cupping and yellowing margins", "india_relevance": "HIGH (Up to 100% crop loss)", "image_detectability": "HIGH", "source": "ICAR-IIHR Bengaluru", "confidence": "HIGH"},
        {"crop": "Tomato", "condition": "Tomato Spider Mites", "category": "Pest Damage", "causal_agent": "Tetranychus urticae", "symptoms": "Fine yellow-white stippling and webbing", "india_relevance": "HIGH (Dry weather open/polyhouse pest)", "image_detectability": "HIGH", "source": "ICAR-NBAIR Bengaluru", "confidence": "HIGH"},
        {"crop": "Tomato", "condition": "Tomato Healthy", "category": "Healthy", "causal_agent": "None", "symptoms": "Healthy compound foliage with serrated leaflets", "india_relevance": "HIGH", "image_detectability": "HIGH", "source": "ICAR-IIHR Bengaluru", "confidence": "HIGH"},
        {"crop": "Potato", "condition": "Potato Early Blight", "category": "Fungal Disease", "causal_agent": "Alternaria solani", "symptoms": "Concentric target spots on older leaflets", "india_relevance": "HIGH (UP, Bihar, Punjab, Bengal)", "image_detectability": "HIGH", "source": "ICAR-CPRI Shimla", "confidence": "HIGH"},
        {"crop": "Potato", "condition": "Potato Late Blight", "category": "Fungal Disease", "causal_agent": "Phytophthora infestans", "symptoms": "Water-soaked black lesions on leaf tips", "india_relevance": "HIGH (Major potato epidemic disease)", "image_detectability": "HIGH", "source": "ICAR-CPRI Shimla", "confidence": "HIGH"},
        {"crop": "Potato", "condition": "Potato Healthy", "category": "Healthy", "causal_agent": "None", "symptoms": "Lush green pinnate foliage", "india_relevance": "HIGH", "image_detectability": "HIGH", "source": "ICAR-CPRI Shimla", "confidence": "HIGH"},
        {"crop": "Chilli", "condition": "Chilli Leaf Curl", "category": "Viral Disease", "causal_agent": "ChiLCV (Begomovirus)", "symptoms": "Upward leaf curling, boat cupping and vein clearing", "india_relevance": "HIGH (50-90% yield loss in AP, Telangana, Karnataka)", "image_detectability": "HIGH", "source": "ICAR-IIHR Bengaluru", "confidence": "HIGH"},
        {"crop": "Chilli", "condition": "Chilli Bacterial Spot", "category": "Bacterial Disease", "causal_agent": "Xanthomonas campestris", "symptoms": "Dark water-soaked angular spots", "india_relevance": "HIGH (Warm monsoon spells in South India)", "image_detectability": "HIGH", "source": "ICAR-IIHR Bengaluru", "confidence": "HIGH"},
        {"crop": "Chilli", "condition": "Chilli Healthy", "category": "Healthy", "causal_agent": "None", "symptoms": "Glossy dark green lanceolate leaves", "india_relevance": "HIGH", "image_detectability": "HIGH", "source": "ICAR-IIHR Bengaluru", "confidence": "HIGH"},
        {"crop": "Maize", "condition": "Maize Northern Blight", "category": "Fungal Disease", "causal_agent": "Exserohilum turcicum", "symptoms": "Cigar-shaped elliptical necrotic gray-tan lesions", "india_relevance": "HIGH (Karnataka, MP, Bihar, Maharashtra)", "image_detectability": "HIGH", "source": "ICAR-IIMR Ludhiana", "confidence": "HIGH"},
        {"crop": "Maize", "condition": "Maize Common Rust", "category": "Fungal Disease", "causal_agent": "Puccinia sorghi", "symptoms": "Oval cinnamon-brown powdery pustules", "india_relevance": "HIGH (Cool moist environments)", "image_detectability": "HIGH", "source": "ICAR-IIMR Ludhiana", "confidence": "HIGH"},
        {"crop": "Maize", "condition": "Maize Fall Armyworm", "category": "Pest Damage", "causal_agent": "Spodoptera frugiperda", "symptoms": "Shot-hole perforations and ragged window-pane tears", "india_relevance": "HIGH (Major invasive pest across all maize states)", "image_detectability": "HIGH", "source": "ICAR-NBAIR Bengaluru", "confidence": "HIGH"},
        {"crop": "Maize", "condition": "Maize Healthy", "category": "Healthy", "causal_agent": "None", "symptoms": "Broad linear leaf blade with clean midrib", "india_relevance": "HIGH", "image_detectability": "HIGH", "source": "ICAR-IIMR Ludhiana", "confidence": "HIGH"},
        {"crop": "General", "condition": "Nitrogen Deficiency", "category": "Abiotic Stress", "causal_agent": "Soil Nitrogen Deficit", "symptoms": "Uniform pale yellowing starting from lower canopy", "india_relevance": "HIGH (Low organic carbon soils)", "image_detectability": "HIGH", "source": "ICAR-IISS Bhopal", "confidence": "HIGH"},
        {"crop": "General", "condition": "Drought Stress", "category": "Abiotic Stress", "causal_agent": "Soil Water Deficit", "symptoms": "Inward leaf rolling, loss of turgor, scorched margins", "india_relevance": "HIGH (Affects 55% rainfed area)", "image_detectability": "HIGH", "source": "ICAR-CRIDA Hyderabad", "confidence": "HIGH"}
    ]
    df_dis = pd.DataFrame(disease_val)
    df_dis.to_csv(os.path.join(meta_dir, "disease_validation.csv"), index=False)
    df_dis.to_csv(os.path.join(rep_dir, "disease_validation_report.csv"), index=False)

    # 3. Source Registry
    sources = [
        {"source_id": "SRC-01", "authority": "ICAR - Indian Council of Agricultural Research", "source_title": "Handbook of Agriculture & Crop Protection Protocols", "source_url": "https://icar.org.in/", "publication_year": 2023, "verification_notes": "Apex national agricultural research body in India."},
        {"source_id": "SRC-02", "authority": "ICAR - National Rice Research Institute (NRRI), Cuttack", "source_title": "Rice Diseases and IPM in India", "source_url": "https://icar-nrri.in/", "publication_year": 2022, "verification_notes": "National institute for rice pathology and blast/blight research."},
        {"source_id": "SRC-03", "authority": "ICAR - Indian Institute of Wheat and Barley Research (IIWBR), Karnal", "source_title": "Wheat Pathology & Rust Surveillance Bulletins", "source_url": "https://iiwbr.icar.gov.in/", "publication_year": 2024, "verification_notes": "National rust surveillance authority."},
        {"source_id": "SRC-04", "authority": "ICAR - Central Institute for Cotton Research (CICR), Nagpur", "source_title": "Cotton Diseases & Pest Identification Manual", "source_url": "https://cicr.icar.gov.in/", "publication_year": 2023, "verification_notes": "National authority for cotton pathology and leaf curl virus."},
        {"source_id": "SRC-05", "authority": "ICAR - Indian Institute of Horticultural Research (IIHR), Bengaluru", "source_title": "Vegetable Crop Disease Diagnostic Atlas", "source_url": "https://iihr.res.in/", "publication_year": 2023, "verification_notes": "National research center for tomato and chilli pathology."},
        {"source_id": "SRC-06", "authority": "ICAR - Central Potato Research Institute (CPRI), Shimla", "source_title": "Potato Diseases in India: Identification and Management", "source_url": "https://cpri.icar.gov.in/", "publication_year": 2022, "verification_notes": "Authoritative research on Early and Late Blight."},
        {"source_id": "SRC-07", "authority": "ICAR - Indian Institute of Maize Research (IIMR), Ludhiana", "source_title": "Maize Diseases and Fall Armyworm Advisory in India", "source_url": "https://iimr.icar.gov.in/", "publication_year": 2023, "verification_notes": "National institute for maize foliar blight and rust."},
        {"source_id": "SRC-08", "authority": "ICAR - National Bureau of Agricultural Insect Resources (NBAIR), Bengaluru", "source_title": "Invasive Pests & Biological Control Repository", "source_url": "https://www.nbair.res.in/", "publication_year": 2024, "verification_notes": "National database on Fall Armyworm and agricultural insect pests."},
        {"source_id": "SRC-09", "authority": "PlantVillage Botanical Pathology Benchmark Dataset", "source_title": "PlantVillage Open Access Leaf Disease Image Dataset", "source_url": "https://plantvillage.psu.edu/", "publication_year": 2016, "verification_notes": "Open access scientific reference dataset with laboratory validations."}
    ]
    df_src = pd.DataFrame(sources)
    df_src.to_csv(os.path.join(meta_dir, "source_registry.csv"), index=False)
    print("All research metadata tables successfully built!")

if __name__ == "__main__":
    base_dir = r"C:\Users\DELL\.gemini\antigravity\scratch\crop_health_ml"
    build_all_research_tables(base_dir)
